name: Build Flutter APK

on:
  push:
    branches: [ "main", "master", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
          cache: true

      - name: Crear soporte de Android
        run: flutter create . --platforms=android --org com.example

      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar APK en Release
        run: flutter build apk --release

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
